debug: false

server:
   port: 9090
   tomcat:
     uri-encoding: UTF-8
   servlet:
     context-path: /cybredis
spring:
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  application:
    name: cybredis
  security:
    user:
      name: admin
      password: $2a$10$slVrHXE1cvyUnZSLskAMp.A5.g057mTaU7GwP6jdyU7Df/3P/d6DK
      roles: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ""
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 8
        max-wait: -1ms

logging:
  level:
    com:
      cyb:
        blogserver:
          dao: debug