debug: false

web:
  upload-path: F:/log/

server:
   port: 9091
   tomcat:
     uri-encoding: UTF-8
   servlet:
     context-path: /goodsms
spring:
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  application:
    name: goodsms
  datasource:
    password: goodsms
    username: goodsms
    url: jdbc:mysql://114.115.134.1:3306/goodsms?serverTimezone=GMT%2B8&useUnicode=true$characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    minIdle: 5
    maxActive: 20
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # 上传文件总的最大值
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 2MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      cyb:
        blogserver:
          dao: debug